# Generated by Django 5.0.14 on 2026-05-15 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garagem", "0011_rename_cardapio_to_veiculo"),
        ("home", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ex: (38) 99999-9999",
                        max_length=20,
                    ),
                ),
                ("cep", models.CharField(blank=True, default="", max_length=10)),
                ("endereco", models.CharField(blank=True, default="", max_length=200)),
                ("numero", models.CharField(blank=True, default="", max_length=20)),
                (
                    "complemento",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("cidade", models.CharField(blank=True, default="", max_length=100)),
                ("estado", models.CharField(blank=True, default="", max_length=2)),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Somente para emissão de nota fiscal.",
                        max_length=14,
                    ),
                ),
                (
                    "aceita_marketing",
                    models.BooleanField(
                        default=False,
                        help_text="Receber ofertas e novidades por e-mail.",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricoInteresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_snapshot",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "preco_snapshot",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "foto_snapshot",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("primeira_marcacao", models.DateTimeField(auto_now_add=True)),
                ("ultima_marcacao", models.DateTimeField(auto_now=True)),
                ("vezes_marcado", models.PositiveIntegerField(default=1)),
                (
                    "veiculo_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historicos",
                        to="garagem.veiculo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_interesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-ultima_marcacao"],
                "unique_together": {("user", "veiculo_item")},
            },
        ),
    ]
