# Generated by Django 5.0.14 on 2026-05-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acessorios", "0003_rename_officeitem_to_acessorio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acessorio",
            name="foto",
            field=models.ImageField(
                blank=True,
                default="fotos_acessorios/default.png",
                null=True,
                upload_to="fotos_acessorios/",
            ),
        ),
        migrations.AlterField(
            model_name="acessorio",
            name="tipo_item",
            field=models.CharField(
                choices=[
                    ("PROD", "Produto Automotivo"),
                    ("SERV", "Serviço Automotivo"),
                ],
                default="PROD",
                max_length=4,
            ),
        ),
    ]
