# Generated by Django 5.0.14 on 2026-05-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acessorios", "0004_alter_acessorio_foto_alter_acessorio_tipo_item"),
        ("cart", "0001_initial"),
        ("garagem", "0011_rename_cardapio_to_veiculo"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="cart_cartitem_either_veiculo_or_acessorio_item",
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("acessorio_item__isnull", True),
                        ("veiculo_item__isnull", False),
                    ),
                    models.Q(
                        ("acessorio_item__isnull", False),
                        ("veiculo_item__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="cart_cartitem_either_veiculo_or_acessorio_item",
            ),
        ),
    ]
