# Generated by Django 5.0.14 on 2026-05-15 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', "0008_alter_cardapio_promocao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cardapio",
            options={"ordering": ["-adicionado"]},
        ),
        migrations.AddField(
            model_name="cardapio",
            name="ano_fabricacao",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1950),
                    django.core.validators.MaxValueValidator(2027),
                ],
            ),
        ),
        migrations.AddField(
            model_name="cardapio",
            name="ano_modelo",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1950),
                    django.core.validators.MaxValueValidator(2028),
                ],
            ),
        ),
        migrations.AddField(
            model_name="cardapio",
            name="cambio",
            field=models.CharField(
                choices=[
                    ("MAN", "Manual"),
                    ("AUT", "Automático"),
                    ("CVT", "CVT"),
                    ("AUM", "Automatizado"),
                ],
                default="AUT",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="cardapio",
            name="combustivel",
            field=models.CharField(
                choices=[
                    ("FLEX", "Flex"),
                    ("GAS", "Gasolina"),
                    ("DIE", "Diesel"),
                    ("HIB", "Híbrido"),
                    ("ELE", "Elétrico"),
                    ("GNV", "GNV"),
                ],
                default="FLEX",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="cardapio",
            name="cor",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="cardapio",
            name="marca",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="cardapio",
            name="modelo",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="cardapio",
            name="quilometragem",
            field=models.PositiveIntegerField(
                blank=True, help_text="KM rodados", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cardapio",
            name="nome",
            field=models.CharField(help_text="Ex: Honda Civic EXL 2.0", max_length=200),
        ),
        migrations.AlterField(
            model_name="cardapio",
            name="preco",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cardapio",
            name="promocao",
            field=models.CharField(
                choices=[("S", "Sim"), ("N", "Não")], default="N", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="cardapio",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ALL", "Todos"),
                    ("SUV", "SUV"),
                    ("SED", "Sedan"),
                    ("HAT", "Hatch"),
                    ("PIC", "Picape"),
                    ("UTI", "Utilitário"),
                    ("ESP", "Esportivo"),
                ],
                default="ALL",
                max_length=50,
            ),
        ),
    ]
