# Generated by Django 5.0.14 on 2026-05-15 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', "0009_alter_cardapio_options_cardapio_ano_fabricacao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardapioFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="fotos_cardapio_galeria/")),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("principal", models.BooleanField(default=False)),
                ("adicionado", models.DateTimeField(auto_now_add=True)),
                ("cardapio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="garagem.cardapio",
                    ),
                ),
            ],
            options={
                "ordering": ["cardapio_id", "ordem"],
            },
        ),
    ]
